name: Download APK and Commit

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download APK
        run: |
          curl -L -o frida-server-17.9.6-android-arm64.xz "https://github.com/frida/frida/releases/download/17.9.6/frida-server-17.9.6-android-arm64.xz"
      
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add frida-server-17.9.6-android-arm64.xz
          git commit -m "Add Frida Launcher APK" || echo "No changes"
          git push
