name: Download APK and Commit

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download file
        run: |
          curl -L -o frida-gadget-17.9.6-android-arm64.so.xz "https://github.com/frida/frida/releases/download/17.9.6/frida-gadget-17.9.6-android-arm64.so.xz"
      
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add frida-gadget-17.9.6-android-arm64.so.xz
          git commit -m "Add Frida gadget" || echo "No changes"
          git push
